"""empty message

Revision ID: 655f37ad02dd
Revises: ed0d6fda084a
Create Date: 2020-08-04 14:42:41.261701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '655f37ad02dd'
down_revision = 'ed0d6fda084a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'organization', 'user', ['owner_id'], ['id'])
    op.add_column('user', sa.Column('foreign_languages', sa.String(), nullable=True))
    op.drop_column('user', 'foreign_languges')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('foreign_languges', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', 'foreign_languages')
    op.drop_constraint(None, 'organization', type_='foreignkey')
    # ### end Alembic commands ###
