"""empty message

Revision ID: ed0d6fda084a
Revises: 
Create Date: 2020-06-26 18:50:13.757258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed0d6fda084a'
down_revision = '8204aee76d9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume', sa.Column('content', sa.String(), nullable=True))
    op.drop_column('resume', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('resume', 'content')
    # ### end Alembic commands ###
